name: pr environment

on: pull_request

jobs:
  pr-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create PR Environment
        uses: ./.github/actions/pr-environment
      - name: Post Link to Created PR
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "Hello World"
