on: [pull_request, push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action: [build, lint, unit-test, integration-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run ${{ matrix.action }}
  prerelease:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - run: npm version 0.0.0-${{ github.sha }} --git-tag-version=false --tag=${{ github.ref }}
      - run: npm run publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  pr-environment:
    if: github.event_name	== 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pr-environment
