on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run unit-test
      - run: npm run integration-test
      - run: npm version ${{ steps.version.outputs.version }} --git-tag-version=false
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
