on:
  release:
    types:
      - created

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        run: echo ::set-output name=version::${GITHUB_REF:10}
      - run: ${{ steps.version.outputs.version }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run unit-test
      - run: npm run integration-test
      - run: echo "npm run publish"
